name: CI Workflow

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Code
        uses: actions/checkout

      - name: Setup Python Environment
        uses: actions/setup-python
        with:
          python-version: "3.10"
      
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pygame xvfb

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov flake8 black pygame


      - name: Check Code Formatting with Black
        run: black --check --diff .

      - name: Lint Code with Flake8 (1)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=30 --max-line-length=100 --statistics
        
      - name: Run Tests with PyTest
        run: xvfb-run -a pytest --cov=./ --cov-report=xml
